#!/usr/bin/env bash

function test_latest_vesion () {
    editor="$1"
    hash "${editor}" >/dev/null 2>&1
    if [ $? -ne 0 ]; then
        editor=""
    fi
    for crate_dir in $(cat Cargo.toml | grep "^[ ]\+\"" | tr -d '[", ]'); do
        crate="$(echo ${crate_dir} | cut -d'/' -f 2)"
        commit_id="$(git log --pretty=oneline -1 ${crate_dir} | cut -c 1-7)"
        printf "Commit %s for %s\n" "${commit_id}" "${crate}"
        find . -mindepth 2 -name "Cargo.toml" \
                -exec grep -H "${crate}[^-a-Z0-9_]" {} \; \
                | grep sharelibs | grep rev | grep -v "${commit_id}" \
                | while read cargoline; do
            printf "\tOutdated: %s\n" "${cargoline}"
            if [ -n "${editor}" ]; then
                cargotoml="$(echo "${cargoline}"| awk -F':' '{ print $1 }')"
                [ -n "${editor}" ] && "${editor}" ${cargotoml}
            fi
        done
    done
}

function main () {
    test_latest_vesion "$1"
}

main "$@"
