[package]
name = "engine"
version = "0.6.0"
authors = ["Cryptape Technologies <arch@cryptape.com>"]

[dependencies]
libproto = { git = "https://github.com/cryptape/cita-sharelibs.git", rev = "ec04796" }
util = { git = "https://github.com/cryptape/cita-sharelibs.git", rev = "6a5e287" }
protobuf = { version = "^1.0.0" }
cita-crypto = { git = "https://github.com/cryptape/cita-sharelibs.git", rev = "c6b8ef8" }
engine_json = { git = "https://github.com/cryptape/cita-sharelibs.git", rev = "87533ee" }
proof = { git = "https://github.com/cryptape/cita-sharelibs.git", rev = "df4c60e" }
pubsub = { git = "https://github.com/cryptape/cita-sharelibs.git", rev = "11e8929" }
