[package]
name = "pubsub_zeromq"
version = "0.1.0"
authors = ["Cryptape Technologies <arch@cryptape.com>"]

[dependencies.zmq]
version = "0.8"
default-features = false
features = []

[dependencies]
log = "0.3"
