[package]
name = "cita-ed25519"
version = "0.6.0"
authors = ["Cryptape Technologies <arch@cryptape.com>"]

[dependencies]
rustc-serialize = "0.3"
sodiumoxide = { git = "https://github.com/cryptape/sodiumoxide.git", rev = "c324e11a2db461ec6878c55bd6616f75b2e4d16a" }
util = { git = "https://github.com/cryptape/cita-sharelibs.git", rev = "47da817" }
rlp = { git = "https://github.com/cryptape/cita-sharelibs.git", rev = "77e2c45" }
serde = "1.0"
bincode = "0.8.0"
