[package]
name = "tx_pool"
version = "0.6.0"
authors = ["Cryptape Technologies <arch@cryptape.com>"]

[dependencies]
libproto = { path = "../../serialize/libproto" }
util = { path = "../../common/util" }
cita-crypto = { path = "../../cryptography/cita-crypto" }
