[package]
description = "proto"
name = "libproto"
version = "0.6.0"
authors = ["Cryptape Technologies <arch@cryptape.com>"]

[dependencies]
protobuf = { version = "^1.0.0"}
cita-crypto = { path = "../../cryptography/cita-crypto" }
util = { path = "../../common/util" }
rustc-serialize = "0.3"
rlp = { path = "../../serialize/rlp" }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
log = "0.3"
